### ISSUE TITLE
Self hostable version 

### ISSUE THREAD

**Issue by microsoftly** [metz-sh/simulacrum#25]
I love the product and the dependency injection solution fits in perfectly with my use case. 

Because of data controls at my org, we can't ship these data off our servers. Is there a way we can host this with our local code without needing the IDE? Possibly with either a local setup or some vscode extension or similar?

**Comment by iostreamer-X** [comment]
Hey! The use-case makes perfect sense. Are you looking to simply run this locally or want a self-hosted on prem solution for your org?

I ask because adding support to run this locally with persistence is pretty straightforward. But to do it across the org, with user and access management is a bit trickier.

Would love to know more how you plan to use this!

**Comment by microsoftly** [comment]
Honestly, with where you are I think MVP would be best. 

It's clear to me that you're building the basis of a business, but not necessarily a hypergrowth one. Open source here makes a ton of business value sense for you - allow companies to expand and build on what you have and you can charge for support or having a hosted version. They'll let you know which items are higher priority or just building it themselves (e.g. " we need RBAC, ability to share replays across teams, etc ...)

Step one is to reduce any friction to allowing them to try out your product without ever needing to interact with you.  You'll win developers over and if it can be self hosted, (some) questions about telemetry and security go away.

**Comment by iostreamer-X** [comment]
Hey! 

Actually the business is quite different. [metz.sh](https://metz.sh) aims to be figma for engineers:
- Reuse workflows built by other team members. So if I designed the auth service, and you are now building the core, you can simply "import" my design.
- Democratise your design and enable the entire team to give feedback, asynchronously.
- Version control your design like you do code. PRs, releases, reviews etc.

That being said, it still makes sense to enable an on-prem setup. Especially to try it out on your own designs, safely.

I will be forking the [hosted app](https://metz.sh), stripping off telemetry and analytics. And make it available through a simple docker command.
Just provide the database_url(or use docker compose), and the app simply runs in an air gapped manner. Playground and embeds still work out of the box.

> Step one is to reduce any friction to allowing them to try out your product without ever needing to interact with you.

Agreed. My focus is to create a "Quickstart" for running locally/on-prem, with max 3 steps.

Lemme know if this aligns with your requirements. 

PS: The source for this will be open under AGPL for transparency.

**Comment by taras** [comment]
I'm also looking to self-host. I'm very excited bout this.

**Comment by iostreamer-X** [comment]
I come bearing good news! You can now self host the [app](https://app.metz.sh)!

Check out the repository [here](https://github.com/metz-sh/simulacrum-self-host) and simply follow the instructions. Please reach out if something breaks!

**Comment by taras** [comment]
Amazing work! Thank you
